// ──────────────────────────────────────────────────────────────────────────────
// PLACEHOLDER: firebase_options.dart
//
// This file is AUTO-GENERATED by the FlutterFire CLI:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Steps to generate:
//   1. Create a Firebase project at https://console.firebase.google.com
//   2. Enable Phone Authentication (Authentication → Sign-in methods → Phone)
//   3. Create a Firestore database (Build → Firestore Database)
//   4. Run: dart pub global activate flutterfire_cli
//   5. Run: flutterfire configure --project=YOUR_PROJECT_ID
//      (This generates this file and downloads google-services.json for Android
//       and GoogleService-Info.plist for iOS)
//
// DO NOT commit real API keys to public repositories.
// ──────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Web App Firebase configuration from Console ────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHBXIhINSwa0UWg-2OQgp-XCvXnA2teB4',
    appId: '1:1063393728632:web:5ec49402c375903fc5b58d',
    messagingSenderId: '1063393728632',
    projectId: 'yourca-31546',
    authDomain: 'yourca-31546.firebaseapp.com',
    storageBucket: 'yourca-31546.firebasestorage.app',
    measurementId: 'G-V8697QL3NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey1234567890Android',
    appId: '1:1234567890:android:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'yourca-31546',
    storageBucket: 'yourca-31546.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey1234567890iOS',
    appId: '1:1234567890:ios:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'yourca-31546',
    storageBucket: 'yourca-31546.firebasestorage.app',
    iosClientId: '1234567890-abcdef.apps.googleusercontent.com',
    iosBundleId: 'com.yourca.app',
  );
}
