import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/ipo_model.dart';

final selectedIpoCategoryProvider = StateProvider<IpoCategory?>((ref) => null);
final selectedIpoStatusProvider = StateProvider<IpoStatus?>((ref) => null);
final ipoSearchQueryProvider = StateProvider<String>((ref) => '');
final bookmarkedIpoIdsProvider = StateProvider<Set<String>>((ref) => {});

final rawIpoListProvider = Provider<List<IpoItem>>((ref) {
  final now = DateTime.now();
  return [
    IpoItem(
      id: 'ipo_premier_energies',
      name: 'Premier Energies Limited',
      symbol: 'PREMIERENE',
      logoEmoji: '☀️',
      sector: 'Solar PV Module & Cell Manufacturing',
      category: IpoCategory.mainline,
      status: IpoStatus.ongoing,
      priceBandMin: 427.0,
      priceBandMax: 450.0,
      lotSize: 33,
      issueSizeCr: 2830.40,
      faceValue: 1.0,
      gmpAmount: 430.0,
      gmpPercent: 95.55,
      gmpTrend: GmpTrend.up,
      openDate: now.subtract(const Duration(days: 1)),
      closeDate: now.add(const Duration(days: 2)),
      allotmentDate: now.add(const Duration(days: 3)),
      refundDate: now.add(const Duration(days: 4)),
      listingDate: now.add(const Duration(days: 5)),
      subscription: const IpoSubscription(
        qib: 216.67,
        nii: 50.04,
        retail: 7.68,
        employee: 11.42,
        total: 74.38,
        updatedAt: 'Live (5:00 PM)',
      ),
      financials: const [
        IpoFinancialYear(year: 'FY22', revenueCr: 622.8, patCr: -14.4, netWorthCr: 210.5, assetsCr: 840.1),
        IpoFinancialYear(year: 'FY23', revenueCr: 1463.2, patCr: 13.3, netWorthCr: 254.2, assetsCr: 1210.8),
        IpoFinancialYear(year: 'FY24', revenueCr: 3143.8, patCr: 231.4, netWorthCr: 520.1, assetsCr: 2450.4),
      ],
      peRatio: 38.4,
      eps: 11.7,
      ronw: 44.5,
      marketCapCr: 20280.0,
      registrarName: 'KFin Technologies Limited',
      registrarUrl: 'https://ris.kfintech.com/ipostatus/',
      about: 'Premier Energies is India\'s 2nd largest integrated solar cell and solar module manufacturer with over 29 years of experience.',
      objectsOfIssue: [
        'Investment in TOPCon solar cell manufacturing facility in Hyderabad',
        'General corporate purposes'
      ],
    ),
    IpoItem(
      id: 'ipo_orient_tech',
      name: 'Orient Technologies Limited',
      symbol: 'ORIENTTECH',
      logoEmoji: '💻',
      sector: 'IT Infrastructure & Cloud Services',
      category: IpoCategory.mainline,
      status: IpoStatus.ongoing,
      priceBandMin: 195.0,
      priceBandMax: 206.0,
      lotSize: 72,
      issueSizeCr: 214.76,
      faceValue: 10.0,
      gmpAmount: 85.0,
      gmpPercent: 41.26,
      gmpTrend: GmpTrend.up,
      openDate: now.subtract(const Duration(days: 2)),
      closeDate: now.add(const Duration(days: 1)),
      allotmentDate: now.add(const Duration(days: 2)),
      refundDate: now.add(const Duration(days: 3)),
      listingDate: now.add(const Duration(days: 4)),
      subscription: const IpoSubscription(
        qib: 189.90,
        nii: 300.60,
        retail: 66.87,
        total: 151.71,
        updatedAt: 'Live (5:00 PM)',
      ),
      financials: const [
        IpoFinancialYear(year: 'FY22', revenueCr: 467.4, patCr: 33.5, netWorthCr: 102.1, assetsCr: 240.0),
        IpoFinancialYear(year: 'FY23', revenueCr: 535.2, patCr: 38.3, netWorthCr: 135.4, assetsCr: 290.0),
        IpoFinancialYear(year: 'FY24', revenueCr: 602.9, patCr: 41.4, netWorthCr: 172.8, assetsCr: 345.0),
      ],
      peRatio: 20.7,
      eps: 9.95,
      ronw: 24.0,
      marketCapCr: 858.0,
      registrarName: 'Link Intime India Pvt Ltd',
      registrarUrl: 'https://linkintime.co.in/initial_offer/public-issues.html',
      about: 'Orient Technologies provides IT infrastructure solutions, Cloud services, and Data Center transformation across India.',
      objectsOfIssue: [
        'Acquisition of office premises in Navi Mumbai',
        'Funding capital expenditure for Network Operating Centre (NOC)',
        'General corporate purposes'
      ],
    ),
    IpoItem(
      id: 'ipo_baazar_style',
      name: 'Baazar Style Retail Limited',
      symbol: 'STYLEBAAZAR',
      logoEmoji: '🛍️',
      sector: 'Value Fashion Retail',
      category: IpoCategory.mainline,
      status: IpoStatus.ongoing,
      priceBandMin: 370.0,
      priceBandMax: 389.0,
      lotSize: 38,
      issueSizeCr: 834.68,
      faceValue: 5.0,
      gmpAmount: 110.0,
      gmpPercent: 28.28,
      gmpTrend: GmpTrend.up,
      openDate: now.subtract(const Duration(days: 1)),
      closeDate: now.add(const Duration(days: 2)),
      allotmentDate: now.add(const Duration(days: 3)),
      refundDate: now.add(const Duration(days: 4)),
      listingDate: now.add(const Duration(days: 5)),
      subscription: const IpoSubscription(
        qib: 34.6,
        nii: 28.4,
        retail: 9.1,
        total: 20.4,
        updatedAt: 'Live (5:00 PM)',
      ),
      financials: const [
        IpoFinancialYear(year: 'FY22', revenueCr: 551.2, patCr: 0.8, netWorthCr: 120.4, assetsCr: 480.0),
        IpoFinancialYear(year: 'FY23', revenueCr: 788.0, patCr: 5.1, netWorthCr: 142.1, assetsCr: 610.0),
        IpoFinancialYear(year: 'FY24', revenueCr: 972.9, patCr: 21.9, netWorthCr: 210.5, assetsCr: 820.0),
      ],
      peRatio: 132.0,
      eps: 2.94,
      ronw: 10.4,
      marketCapCr: 2900.0,
      registrarName: 'Link Intime India Pvt Ltd',
      registrarUrl: 'https://linkintime.co.in/initial_offer/public-issues.html',
      about: 'Baazar Style Retail (Style Baazar) is the fastest-growing value fashion retailer in Eastern India backed by Rakesh Jhunjhunwala\'s Rekha Jhunjhunwala.',
      objectsOfIssue: [
        'Prepayment or repayment of certain borrowings',
        'General corporate purposes'
      ],
    ),
    IpoItem(
      id: 'ipo_gala_precision',
      name: 'Gala Precision Engineering',
      symbol: 'GALAPREC',
      logoEmoji: '⚙️',
      sector: 'Precision Engineering & Springs',
      category: IpoCategory.mainline,
      status: IpoStatus.ongoing,
      priceBandMin: 503.0,
      priceBandMax: 529.0,
      lotSize: 28,
      issueSizeCr: 167.93,
      faceValue: 10.0,
      gmpAmount: 265.0,
      gmpPercent: 50.09,
      gmpTrend: GmpTrend.up,
      openDate: now.subtract(const Duration(days: 1)),
      closeDate: now.add(const Duration(days: 2)),
      allotmentDate: now.add(const Duration(days: 3)),
      refundDate: now.add(const Duration(days: 4)),
      listingDate: now.add(const Duration(days: 5)),
      subscription: const IpoSubscription(
        qib: 12.5,
        nii: 42.1,
        retail: 18.2,
        total: 20.1,
        updatedAt: 'Live (5:00 PM)',
      ),
      financials: const [
        IpoFinancialYear(year: 'FY22', revenueCr: 145.2, patCr: 14.8, netWorthCr: 65.4, assetsCr: 130.0),
        IpoFinancialYear(year: 'FY23', revenueCr: 165.4, patCr: 24.2, netWorthCr: 88.2, assetsCr: 155.0),
        IpoFinancialYear(year: 'FY24', revenueCr: 202.5, patCr: 22.3, netWorthCr: 108.9, assetsCr: 185.0),
      ],
      peRatio: 23.7,
      eps: 22.3,
      ronw: 20.5,
      marketCapCr: 670.0,
      registrarName: 'Link Intime India Pvt Ltd',
      registrarUrl: 'https://linkintime.co.in/initial_offer/public-issues.html',
      about: 'Gala Precision manufactures precision components like disc & diaphragm springs, high-fasteners for wind turbines and hydro power.',
      objectsOfIssue: [
        'Setting up a new facility in Vallam-Vadagal, Tamil Nadu',
        'Funding capital expenditure for purchase of equipment'
      ],
    ),
    IpoItem(
      id: 'ipo_swiggy',
      name: 'Swiggy Limited',
      symbol: 'SWIGGY',
      logoEmoji: '🛵',
      sector: 'E-Commerce / Consumer Tech',
      category: IpoCategory.mainline,
      status: IpoStatus.listed,
      priceBandMin: 371.0,
      priceBandMax: 390.0,
      lotSize: 38,
      issueSizeCr: 11327.43,
      faceValue: 1.0,
      gmpAmount: 45.0,
      gmpPercent: 11.54,
      gmpTrend: GmpTrend.up,
      openDate: now.subtract(const Duration(days: 30)),
      closeDate: now.subtract(const Duration(days: 27)),
      allotmentDate: now.subtract(const Duration(days: 25)),
      refundDate: now.subtract(const Duration(days: 24)),
      listingDate: now.subtract(const Duration(days: 23)),
      subscription: const IpoSubscription(
        qib: 6.02,
        nii: 2.41,
        retail: 1.14,
        employee: 1.56,
        total: 3.59,
        updatedAt: 'Listed',
      ),
      financials: const [
        IpoFinancialYear(year: 'FY22', revenueCr: 6115.6, patCr: -3628.9, netWorthCr: 5410.2, assetsCr: 8940.1),
        IpoFinancialYear(year: 'FY23', revenueCr: 8714.5, patCr: -4179.3, netWorthCr: 4120.5, assetsCr: 9110.8),
        IpoFinancialYear(year: 'FY24', revenueCr: 11247.4, patCr: -2350.2, netWorthCr: 3980.1, assetsCr: 9850.4),
      ],
      peRatio: 0.0,
      eps: -12.4,
      ronw: -59.0,
      marketCapCr: 87500.0,
      registrarName: 'Link Intime India Pvt Ltd',
      registrarUrl: 'https://linkintime.co.in/initial_offer/public-issues.html',
      about: 'Swiggy is a leading consumer technology platform offering food delivery, quick commerce (Instamart), out-of-home consumption (Dineout).',
      objectsOfIssue: [
        'Investment in technology & cloud infrastructure',
        'Expansion of Dark Stores network for Instamart'
      ],
      listedPrice: 420.0,
      listingGainPercent: 7.69,
    ),
    IpoItem(
      id: 'ipo_hyundai',
      name: 'Hyundai Motor India Limited',
      symbol: 'HYUNDAI',
      logoEmoji: '🚗',
      sector: 'Automobile',
      category: IpoCategory.mainline,
      status: IpoStatus.listed,
      priceBandMin: 1860.0,
      priceBandMax: 1960.0,
      lotSize: 7,
      issueSizeCr: 27870.16,
      faceValue: 10.0,
      gmpAmount: 125.0,
      gmpPercent: 6.38,
      gmpTrend: GmpTrend.flat,
      openDate: now.subtract(const Duration(days: 40)),
      closeDate: now.subtract(const Duration(days: 37)),
      allotmentDate: now.subtract(const Duration(days: 35)),
      refundDate: now.subtract(const Duration(days: 34)),
      listingDate: now.subtract(const Duration(days: 33)),
      subscription: const IpoSubscription(
        qib: 6.97,
        nii: 0.60,
        retail: 0.50,
        employee: 1.74,
        total: 2.37,
        updatedAt: 'Listed',
      ),
      financials: const [
        IpoFinancialYear(year: 'FY22', revenueCr: 47963.5, patCr: 2901.6, netWorthCr: 14210.0, assetsCr: 22100.0),
        IpoFinancialYear(year: 'FY23', revenueCr: 61436.2, patCr: 4709.3, netWorthCr: 17890.0, assetsCr: 26500.0),
        IpoFinancialYear(year: 'FY24', revenueCr: 69829.1, patCr: 6047.2, netWorthCr: 21540.0, assetsCr: 30120.0),
      ],
      peRatio: 26.2,
      eps: 74.8,
      ronw: 28.1,
      marketCapCr: 159250.0,
      registrarName: 'KFin Technologies Limited',
      registrarUrl: 'https://ris.kfintech.com/ipostatus/',
      about: 'Hyundai Motor India Ltd is the third largest passenger vehicle manufacturer in India, part of Hyundai Motor Group Korea.',
      objectsOfIssue: [
        'Entirely Offer for Sale (OFS) by promoter Hyundai Motor Corporation'
      ],
      listedPrice: 1930.0,
      listingGainPercent: -1.53,
    ),
    IpoItem(
      id: 'ipo_bajaj',
      name: 'Bajaj Housing Finance Ltd',
      symbol: 'BAJAJHFL',
      logoEmoji: '🏠',
      sector: 'NBFC / Housing Finance',
      category: IpoCategory.mainline,
      status: IpoStatus.listed,
      priceBandMin: 66.0,
      priceBandMax: 70.0,
      lotSize: 214,
      issueSizeCr: 6560.0,
      faceValue: 10.0,
      gmpAmount: 75.0,
      gmpPercent: 107.14,
      gmpTrend: GmpTrend.up,
      openDate: now.subtract(const Duration(days: 30)),
      closeDate: now.subtract(const Duration(days: 27)),
      allotmentDate: now.subtract(const Duration(days: 25)),
      refundDate: now.subtract(const Duration(days: 24)),
      listingDate: now.subtract(const Duration(days: 23)),
      subscription: const IpoSubscription(
        qib: 222.4,
        nii: 43.2,
        retail: 7.41,
        total: 67.43,
        updatedAt: 'Closed',
      ),
      financials: const [
        IpoFinancialYear(year: 'FY22', revenueCr: 3767.1, patCr: 709.6, netWorthCr: 6410.0, assetsCr: 53100.0),
        IpoFinancialYear(year: 'FY23', revenueCr: 5664.7, patCr: 1257.8, netWorthCr: 9230.0, assetsCr: 68900.0),
        IpoFinancialYear(year: 'FY24', revenueCr: 7617.7, patCr: 1731.2, netWorthCr: 11420.0, assetsCr: 91400.0),
      ],
      peRatio: 33.6,
      eps: 2.08,
      ronw: 15.2,
      marketCapCr: 58300.0,
      registrarName: 'KFin Technologies Limited',
      registrarUrl: 'https://ris.kfintech.com/ipostatus/',
      about: 'Non-deposit-taking housing finance company providing finance for purchase and renovation of homes and commercial property.',
      objectsOfIssue: [
        'Augment capital base to meet future capital requirements'
      ],
      listedPrice: 150.0,
      listingGainPercent: 114.28,
    ),
    IpoItem(
      id: 'ipo_krn',
      name: 'KRN Heat Exchanger & Refrigeration',
      symbol: 'KRNHEAT',
      logoEmoji: '❄️',
      sector: 'Industrial Manufacturing',
      category: IpoCategory.mainline,
      status: IpoStatus.listed,
      priceBandMin: 209.0,
      priceBandMax: 220.0,
      lotSize: 65,
      issueSizeCr: 341.95,
      faceValue: 10.0,
      gmpAmount: 270.0,
      gmpPercent: 122.73,
      gmpTrend: GmpTrend.up,
      openDate: now.subtract(const Duration(days: 20)),
      closeDate: now.subtract(const Duration(days: 18)),
      allotmentDate: now.subtract(const Duration(days: 16)),
      refundDate: now.subtract(const Duration(days: 15)),
      listingDate: now.subtract(const Duration(days: 14)),
      subscription: const IpoSubscription(
        qib: 253.04,
        nii: 430.2,
        retail: 96.5,
        total: 214.42,
        updatedAt: 'Closed',
      ),
      financials: const [
        IpoFinancialYear(year: 'FY22', revenueCr: 158.2, patCr: 10.9, netWorthCr: 34.5, assetsCr: 98.1),
        IpoFinancialYear(year: 'FY23', revenueCr: 249.9, patCr: 32.3, netWorthCr: 66.8, assetsCr: 142.5),
        IpoFinancialYear(year: 'FY24', revenueCr: 308.3, patCr: 39.1, netWorthCr: 105.9, assetsCr: 198.4),
      ],
      peRatio: 35.2,
      eps: 6.25,
      ronw: 36.9,
      marketCapCr: 1280.0,
      registrarName: 'Bigshare Services Pvt Ltd',
      registrarUrl: 'https://www.bigshareonline.com/ipo_status.html',
      about: 'KRN Heat Exchanger manufactures fin and tube-type heat exchangers for HVAC and refrigeration systems.',
      objectsOfIssue: [
        'Investment in new manufacturing facility in Neemrana, Rajasthan',
        'General corporate purposes'
      ],
      listedPrice: 470.0,
      listingGainPercent: 113.63,
    ),
    IpoItem(
      id: 'ipo_godavari',
      name: 'Godavari Biorefineries Limited',
      symbol: 'GODAVARI',
      logoEmoji: '🌱',
      sector: 'Bio-fuels & Specialty Chemicals',
      category: IpoCategory.mainline,
      status: IpoStatus.upcoming,
      priceBandMin: 334.0,
      priceBandMax: 352.0,
      lotSize: 42,
      issueSizeCr: 554.75,
      faceValue: 10.0,
      gmpAmount: 40.0,
      gmpPercent: 11.36,
      gmpTrend: GmpTrend.up,
      openDate: now.add(const Duration(days: 3)),
      closeDate: now.add(const Duration(days: 6)),
      allotmentDate: now.add(const Duration(days: 7)),
      refundDate: now.add(const Duration(days: 8)),
      listingDate: now.add(const Duration(days: 9)),
      subscription: const IpoSubscription(
        qib: 0.0,
        nii: 0.0,
        retail: 0.0,
        total: 0.0,
        updatedAt: 'Not Started',
      ),
      financials: const [
        IpoFinancialYear(year: 'FY22', revenueCr: 1686.2, patCr: 19.1, netWorthCr: 210.4, assetsCr: 1120.0),
        IpoFinancialYear(year: 'FY23', revenueCr: 2020.1, patCr: 19.6, netWorthCr: 230.1, assetsCr: 1350.0),
        IpoFinancialYear(year: 'FY24', revenueCr: 1686.7, patCr: 12.3, netWorthCr: 242.5, assetsCr: 1410.0),
      ],
      peRatio: 84.2,
      eps: 4.18,
      ronw: 5.07,
      marketCapCr: 1800.0,
      registrarName: 'Link Intime India Pvt Ltd',
      registrarUrl: 'https://linkintime.co.in/initial_offer/public-issues.html',
      about: 'Godavari Biorefineries is a manufacturer of ethanol-based specialty chemicals in India.',
      objectsOfIssue: [
        'Prepayment of borrowings',
        'Capital expenditure for bio-refinery expansion'
      ],
    ),
    IpoItem(
      id: 'ipo_paramount',
      name: 'Paramount Speciality Forgings',
      symbol: 'PARAMOUNT',
      logoEmoji: '⚙️',
      sector: 'Forgings & Engineering (SME)',
      category: IpoCategory.sme,
      status: IpoStatus.ongoing,
      priceBandMin: 57.0,
      priceBandMax: 59.0,
      lotSize: 2000,
      issueSizeCr: 32.34,
      faceValue: 10.0,
      gmpAmount: 22.0,
      gmpPercent: 37.29,
      gmpTrend: GmpTrend.up,
      openDate: now.subtract(const Duration(days: 1)),
      closeDate: now.add(const Duration(days: 2)),
      allotmentDate: now.add(const Duration(days: 3)),
      refundDate: now.add(const Duration(days: 4)),
      listingDate: now.add(const Duration(days: 5)),
      subscription: const IpoSubscription(
        qib: 1.25,
        nii: 12.8,
        retail: 48.5,
        total: 24.1,
        updatedAt: 'Live (5:00 PM)',
      ),
      financials: const [
        IpoFinancialYear(year: 'FY22', revenueCr: 88.5, patCr: 2.1, netWorthCr: 18.2, assetsCr: 45.1),
        IpoFinancialYear(year: 'FY23', revenueCr: 112.4, patCr: 4.8, netWorthCr: 23.0, assetsCr: 54.2),
        IpoFinancialYear(year: 'FY24', revenueCr: 138.2, patCr: 7.2, netWorthCr: 30.2, assetsCr: 68.0),
      ],
      peRatio: 18.5,
      eps: 3.18,
      ronw: 23.8,
      marketCapCr: 120.0,
      registrarName: 'Bigshare Services Pvt Ltd',
      registrarUrl: 'https://www.bigshareonline.com/ipo_status.html',
      about: 'Paramount Speciality Forgings manufactures steel forgings for petrochemicals, oil & gas, valves and fertilizer industries.',
      objectsOfIssue: [
        'Capital expenditure for machinery',
        'Working capital requirements'
      ],
    ),
    IpoItem(
      id: 'ipo_apex',
      name: 'Apex Ecotech Limited',
      symbol: 'APEX',
      logoEmoji: '💧',
      sector: 'Water Treatment (SME)',
      category: IpoCategory.sme,
      status: IpoStatus.upcoming,
      priceBandMin: 71.0,
      priceBandMax: 73.0,
      lotSize: 1600,
      issueSizeCr: 25.54,
      faceValue: 10.0,
      gmpAmount: 38.0,
      gmpPercent: 52.05,
      gmpTrend: GmpTrend.up,
      openDate: now.add(const Duration(days: 4)),
      closeDate: now.add(const Duration(days: 7)),
      allotmentDate: now.add(const Duration(days: 8)),
      refundDate: now.add(const Duration(days: 9)),
      listingDate: now.add(const Duration(days: 10)),
      subscription: const IpoSubscription(
        qib: 0.0,
        nii: 0.0,
        retail: 0.0,
        total: 0.0,
        updatedAt: 'Not Started',
      ),
      financials: const [
        IpoFinancialYear(year: 'FY22', revenueCr: 24.1, patCr: 1.2, netWorthCr: 6.8, assetsCr: 18.2),
        IpoFinancialYear(year: 'FY23', revenueCr: 38.6, patCr: 2.9, netWorthCr: 9.7, assetsCr: 24.5),
        IpoFinancialYear(year: 'FY24', revenueCr: 52.1, patCr: 5.4, netWorthCr: 15.1, assetsCr: 32.8),
      ],
      peRatio: 16.2,
      eps: 4.50,
      ronw: 35.7,
      marketCapCr: 95.0,
      registrarName: 'Skyline Financial Services Pvt Ltd',
      registrarUrl: 'https://www.skylinefta.com/ipo_status.html',
      about: 'Apex Ecotech delivers water and wastewater treatment solutions, ZLD plants, and sludge management systems.',
      objectsOfIssue: [
        'Funding working capital requirements',
        'General corporate purposes'
      ],
    ),
  ];
});

final filteredIpoListProvider = Provider<List<IpoItem>>((ref) {
  final allIpos = ref.watch(rawIpoListProvider);
  final category = ref.watch(selectedIpoCategoryProvider);
  final status = ref.watch(selectedIpoStatusProvider);
  final search = ref.watch(ipoSearchQueryProvider).trim().toLowerCase();
  final bookmarkedIds = ref.watch(bookmarkedIpoIdsProvider);

  return allIpos.map((ipo) => ipo.copyWith(isBookmarked: bookmarkedIds.contains(ipo.id))).where((ipo) {
    if (category != null && ipo.category != category) return false;
    if (status != null && ipo.status != status) return false;
    if (search.isNotEmpty) {
      final matchesName = ipo.name.toLowerCase().contains(search);
      final matchesSymbol = ipo.symbol.toLowerCase().contains(search);
      final matchesSector = ipo.sector.toLowerCase().contains(search);
      if (!matchesName && !matchesSymbol && !matchesSector) return false;
    }
    return true;
  }).toList();
});
